apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: cinema
      username: default
      tlsSkipVerify: true
  - name: Postgres
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    user: analytics
    jsonData:
      database: analytics
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: analytics
